on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Build and Pack
      run: |
        dotnet restore Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj
        dotnet build --configuration Release Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj /p:Version=$GITHUB_REF_NAME
        dotnet pack --configuration Release --include-source Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj /p:Version=$GITHUB_REF_NAME
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Frends.HIT.OpenPGP/bin/Release/*.nupkg
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true