on:
  push:
    tags: ["*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
  
      - name: Build, Pack and Push
        run: |
          dotnet restore Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj
          dotnet build --configuration Release Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj /p:Version=$GITHUB_REF_NAME
          dotnet pack --configuration Release --include-source Frends.HIT.OpenPGP/Frends.HIT.OpenPGP.csproj /p:Version=$GITHUB_REF_NAME
          dotnet nuget push Frends.HIT.OpenPGP/bin/Release/Frends.HIT.OpenPGP.*.nupkg --source ${{ secrets.FRENDS_NUGET_FEED_URL }} --api-key ${{ secrets.FRENDS_NUGET_FEED_KEY }}
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Frends.HIT.OpenPGP/bin/Release/Frends.HIT.OpenPGP.*.nupkg
          name: "Release ${{ github.ref }}"
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          prerelease: false
          draft: false
